### ISSUE TITLE
User cannot request access to NETMANAGER

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#251]
**What were you trying to achieve?**
The user is not able to finish requesting access to netmanager. After filling in the form and hitting "Request" button, nothing happens. An issue ticket (service desk) is here [AIRSD-64]
**What are the expected results?**
User should receive an email informing them that their request has been received. 
**What are the received results?**
Nothing happens. Some error messages are logged on the console as shown below;
![Screenshot 2021-05-02 at 20 31 43](https://user-images.githubusercontent.com/15224992/116822066-7f51cf00-ab85-11eb-932a-3d594fa82299.png)

**What are the steps to reproduce the issue?**
Go to netmanager login screen (staging or production) and click "request access". Fill in the form and hit "Request"
**In what environment did you encounter the issue?**
 - OS: MacOS
 - Version: 10.14.6

**Additional context**
I've tested the backend endpoint (staging) and seems to be working well.

[AIRSD-64]: https://airqoteam.atlassian.net/browse/AIRSD-64

**Comment by Baalmart** [comment]
I guess this works now but for user experience, we now need to add some kind of notification to inform the user about what has just happened. In the current format, the user is not informed since they are just forwarded to the Login page without any guiding notes/alerts about what has just happened. Kind of confusing. cc: @ja-odur @sserurich

**Comment by ja-odur** [comment]
resolved
